---
- name: setup the repositories from the current node
  copy:
    src: /etc/yum.repos.d/
    dest: /etc/yum.repos.d/

- name: copy pem files
  copy:
    src: /var/lib/yum/client-cert.pem
    dest: /var/lib/yum/client-cert.pem
- copy:
    src: /var/lib/yum/client-key.pem
    dest: /var/lib/yum/client-key.pem

- name: remove CentOs repo because of centos conductor image
  shell: yum clean all; rm /etc/yum.repos.d/CentOS*; ls -l /etc/yum.repos.d/;

- name: create needed directories
  shell: mkdir -p /lib/modules/`uname -r` && ln -sf /usr/src/kernels/`uname -r` /lib/modules/`uname -r`/build
  args:
    creates:
      - /lib/modules/`uname -r`
